kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: inguard-admin
  namespace: inguard
subjects:
- kind: ServiceAccount
  name: ns-reconciler-inguard
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
